### ISSUE TITLE
How does a user know the booking was successfull?

### ISSUE THREAD

**Issue by jappeace** [jappeace/rentals#10]
I get redirected to the same page

**Comment by ptkato** [comment]
The redirect means that it's successful, and yes, it's not ideal. What would be the desired approach here? Keep in mind that users don't need to register.

A few suggestions:
* a toast in the redirected to page saying that it was successful;
* a new page altogether; in this case, what info should this page contain?
* let stripe handle it; considering that we don't keep any user info

**Comment by jappeace** [comment]
can we:

1. redirect to a success page,
2. send a confirmation email to the users' email address?

**Comment by ptkato** [comment]
Closed by https://github.com/jappeace/rentals/pull/27
