### ISSUE TITLE
How do (the admin) know a booking has happened?

### ISSUE THREAD

**Issue by jappeace** [jappeace/rentals#13]

**Comment by ptkato** [comment]
New bookings are added to the calendar in the listing admin page, but yes, I can see how that is too subtle and might go unnoticed. What remains is a way to warn the admin that a new booking was made, add some kind of in-app notification system? Maybe rely on email?

**Comment by jappeace** [comment]
an email would be good

**Comment by jappeace** [comment]
could we also make it more clear in the calandar?

**Comment by ptkato** [comment]
Closed by https://github.com/jappeace/rentals/pull/26
