### ISSUE TITLE
Add bulk upload of pics for rentals

### ISSUE THREAD

**Issue by jappeace** [jappeace/rentals#6]

**Comment by ptkato** [comment]
this is already the case, you can pick multiple images for uploading

**Comment by jappeace** [comment]
I get 413 entity to large when wanting to upload 23 pics:

![image](https://github.com/jappeace/rentals/assets/3874017/1ff3208e-744a-41ea-85e5-2da05cc8f36d)

![image](https://github.com/jappeace/rentals/assets/3874017/f6888da9-64ae-4545-a584-098a8713f4c8)

**Comment by ptkato** [comment]
Ah, I see, well, the default max size is 2 megabytes, what would be a desired max size for uploading, if having a max size at all?

**Comment by jappeace** [comment]
if we could support 23 files, it'd be good, i guess bumping it to 30mb would work

**Comment by ptkato** [comment]
Fixed with https://github.com/jappeace/rentals/commit/7e6ca185cc1d0a514b316224f9347b09e24b77c5.
